name: Godot CI/CD Pipeline

on: 
  push:
    branches:
      - main

env:
  EXPORT_NAME: TestGame
  GODOT_VERSION: "4.3"
  ITCH_GAME: test-project-2d-godot
  ITCH_USER: benbenb
jobs:
  export-game:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "HTML5" ./build/web/index.html
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: $EXPORT_NAME"-HTML5"
          path: build/web

  deploy-to-github-pages:
    runs-on: ubuntu-20.04
    needs: export-game
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: $EXPORT_NAME"-HTML5"
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages 
          folder: build/web

  deploy-to-itchio-web:
    runs-on: ubuntu-20.04
    needs: export-game
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: $EXPORT_NAME"-HTML5"
      - name: Deploy to Itch.io (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: $ITCH_GAME
          ITCH_USER: $ITCH_USER
          PACKAGE: build/web
